services:
  eosio:
    build: .
    container_name: eosio_pull_api_node
    ports:
      - "8888:8888"
      - "9876:9876"
      - "9101:9101" # metrics for prometheus
    volumes:
      - eos_data:/mnt/dev/data
      - ./config.ini:/mnt/dev/config.ini:ro
    environment:
      - NODEOS_LOG_LEVEL=info
    networks:
      - eosio_network
    restart: always
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
  grafana:
      image: grafana:latest
      restart: always
      ports:
        - 80:3000
      expose:
        - 80
      volumes:
        - ./grafana/provisioning/:/etc/grafana/provisioning/
        - graf_data:/var/lib/grafana
      env_file:
        - ./grafana/config.monitoring

volumes:
    prom_data:
    graf_data:
    eos_data:

networks:
  eosio_network:
    name: eosio_network