services:
  eosio:
    build: .
    container_name: eosio_pull_api_node
    ports:
      - "8888:8888"
      - "9876:9876"
      - "8080:8080"
    volumes:
      - ./data:/mnt/dev/data
      - ./config.ini:/mnt/dev/config.ini:ro
    environment:
      - NODEOS_LOG_LEVEL=info
    networks:
      - eosio_network
    restart: always

networks:
  eosio_network:
    name: eosio_network

#    driver_opts:
#      type: none
#      o: bind
#      device: .
