services:
  eosio:
    build: .
    container_name: eosio_pull_api_node
    ports:
      - "8888:8888"
      - "9876:9876"
      - "9101:9101" # metrics for prometheus
    volumes:
      - eos_data:/mnt/dev/data
      - ./config.ini:/mnt/dev/config.ini:ro
    environment:
      - NODEOS_LOG_LEVEL=info
    networks:
      - eosio_network
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prom_data:/prometheus
    depends_on:
      - eosio
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
      restart: always
      image: grafana/grafana
      user: '472'
      depends_on:
        - eosio
        - prometheus
      ports:
        - 6000:3000
      volumes:
        - grafanadata:/var/lib/grafanadata
        - ./grafana/provisioning/:/etc/grafana/provisioning/
      env_file:
        - ./grafana/config.monitoring

volumes:
    prom_data:
    grafanadata:
    eos_data:

networks:
  eosio_network:
    name: eosio_network